'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
var _express = require('express');
var _express2 = _interopRequireDefault(_express);
var _products = require('./routes/products');
var _products2 = _interopRequireDefault(_products);
var _productCategories = require('./routes/productCategories');
var _productCategories2 = _interopRequireDefault(_productCategories);
var _sitemap = require('./routes/sitemap');
var _sitemap2 = _interopRequireDefault(_sitemap);
var _theme = require('./routes/theme');
var _theme2 = _interopRequireDefault(_theme);
var _customers = require('./routes/customers');
var _customers2 = _interopRequireDefault(_customers);
var _customerGroups = require('./routes/customerGroups');
var _customerGroups2 = _interopRequireDefault(_customerGroups);
var _orders = require('./routes/orders');
var _orders2 = _interopRequireDefault(_orders);
var _orderStatuses = require('./routes/orderStatuses');
var _orderStatuses2 = _interopRequireDefault(_orderStatuses);
var _shippingMethods = require('./routes/shippingMethods');
var _shippingMethods2 = _interopRequireDefault(_shippingMethods);
var _paymentMethods = require('./routes/paymentMethods');
var _paymentMethods2 = _interopRequireDefault(_paymentMethods);
var _paymentGateways = require('./routes/paymentGateways');
var _paymentGateways2 = _interopRequireDefault(_paymentGateways);
var _settings = require('./routes/settings');
var _settings2 = _interopRequireDefault(_settings);
var _pages = require('./routes/pages');
var _pages2 = _interopRequireDefault(_pages);
var _marks = require('./routes/marks');
var _marks2 = _interopRequireDefault(_marks);
var _models = require('./routes/models');
var _models2 = _interopRequireDefault(_models);
var _years = require('./routes/years');
var _years2 = _interopRequireDefault(_years);
var _engines = require('./routes/engines');
var _engines2 = _interopRequireDefault(_engines);
var _fuels = require('./routes/fuels');
var _fuels2 = _interopRequireDefault(_fuels);
var _pcategories = require('./routes/pcategories');
var _pcategories2 = _interopRequireDefault(_pcategories);
var _tokens = require('./routes/tokens');
var _tokens2 = _interopRequireDefault(_tokens);
var _notifications = require('./routes/notifications');
var _notifications2 = _interopRequireDefault(_notifications);
var _redirects = require('./routes/redirects');
var _redirects2 = _interopRequireDefault(_redirects);
var _files = require('./routes/files');
var _files2 = _interopRequireDefault(_files);
var _apps = require('./routes/apps');
var _apps2 = _interopRequireDefault(_apps);
var _webhooks = require('./routes/webhooks');
var _webhooks2 = _interopRequireDefault(_webhooks);
var _xmlimporter = require('./routes/xmlimporter');
var _xmlimporter2 = _interopRequireDefault(_xmlimporter);
function _interopRequireDefault(obj) {
	return obj && obj.__esModule ? obj : { default: obj };
}

var apiRouter = _express2.default.Router();

new _products2.default(apiRouter);
new _productCategories2.default(apiRouter);
new _sitemap2.default(apiRouter);
new _theme2.default(apiRouter);
new _customers2.default(apiRouter);
new _customerGroups2.default(apiRouter);
new _orders2.default(apiRouter);
new _orderStatuses2.default(apiRouter);
new _shippingMethods2.default(apiRouter);
new _paymentMethods2.default(apiRouter);
new _paymentGateways2.default(apiRouter);
new _settings2.default(apiRouter);
new _pages2.default(apiRouter);
new _marks2.default(apiRouter);
new _models2.default(apiRouter);
new _years2.default(apiRouter);
new _engines2.default(apiRouter);
new _fuels2.default(apiRouter);
new _pcategories2.default(apiRouter);
new _tokens2.default(apiRouter);
new _notifications2.default(apiRouter);
new _redirects2.default(apiRouter);
new _files2.default(apiRouter);
new _apps2.default(apiRouter);
new _webhooks2.default(apiRouter);
new _xmlimporter2.default(apiRouter);
exports.default = apiRouter;
